// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mqBAZ2p9QRKTzOPGX2iMwsJFE_Ty6Z4',
    appId: '1:781649625274:web:890cce49470dee274f0283',
    messagingSenderId: '781649625274',
    projectId: 'push-notification-c1bb8',
    authDomain: 'push-notification-c1bb8.firebaseapp.com',
    storageBucket: 'push-notification-c1bb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OHXo2P2BESSyIUhaHDfy-xoVpk-l17Y',
    appId: '1:781649625274:android:a9ccffa9f27530e14f0283',
    messagingSenderId: '781649625274',
    projectId: 'push-notification-c1bb8',
    storageBucket: 'push-notification-c1bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkL2gKARCE6FhvcVzxA4YYvZpwV-mjOQ',
    appId: '1:781649625274:ios:6ba6cdba76bb054f4f0283',
    messagingSenderId: '781649625274',
    projectId: 'push-notification-c1bb8',
    storageBucket: 'push-notification-c1bb8.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkL2gKARCE6FhvcVzxA4YYvZpwV-mjOQ',
    appId: '1:781649625274:ios:e756e72edca1b3434f0283',
    messagingSenderId: '781649625274',
    projectId: 'push-notification-c1bb8',
    storageBucket: 'push-notification-c1bb8.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp.RunnerTests',
  );
}
